### PR TITLE
tech-debt: fix react router links

### LINKED ISSUE #44: Fix react-router links
**Describe the bug**
Currently, the routes in the app do not include a 'Home' page (Index.jsx).  

**Expected behavior**
- I want to include a home page that is not called in App.jsx
- To do: need to research the best way to link MUI and react-router-dom

### PR DESCRIPTION
**Pull request by dana-rocha**
Closes #44

### CODE REVIEW

File: src/pages/MainPage.jsx [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+                color="text.secondary"
+                paragraph
+              >
+                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
+                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
+                enim ad minim veniam, quis nostrud exercitation ullamco laboris
+                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
+                in reprehenderit in voluptate velit esse cillum dolore eu fugiat
+                nulla pariatur. Excepteur sint occaecat cupidatat non proident,
+                sunt in culpa qui officia deserunt mollit anim id est laborum.
```
Comment (jtyoung84) [inline src/pages/MainPage.jsx:56]: Assume that this will be public facing. So don't use "lorem ipsum" as placeholder text.

**Review by jtyoung84 — CHANGES_REQUESTED** [review]
Don't use "lorem ipsum" as placeholder text

**Review by jtyoung84 — APPROVED** [review]
